[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.4.1", features = ["full"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
